package GUI;

import Characters.Student;
import Data.SchoolDepartment;
import Simulation.Simulation;

/**
 *
 * @author Luca Di Bello
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        gManager = new GuiManager(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInfos = new javax.swing.JPanel();
        labelDate = new javax.swing.JLabel();
        labelTime = new javax.swing.JLabel();
        panelContent = new javax.swing.JPanel();
        bathroomPanel1 = new GUI.BathroomPanel();
        tabPanel = new javax.swing.JTabbedPane();
        logTabContent = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaLog = new javax.swing.JTextArea();
        toiletHoursTabContent = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableStudentBathroomHours = new javax.swing.JTable();
        statusPanel = new javax.swing.JPanel();
        containersPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelSoapFill = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelPaperFill = new javax.swing.JLabel();
        studentStatsPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        labelNoWashTimes = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelNoDryTimes = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelTimesInBathroom = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelInfos.setBackground(new java.awt.Color(204, 204, 255));
        panelInfos.setLayout(new java.awt.GridLayout(2, 1));

        labelDate.setText("Current Date:");
        labelDate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelInfos.add(labelDate);

        labelTime.setText("Current Time:");
        panelInfos.add(labelTime);

        getContentPane().add(panelInfos, java.awt.BorderLayout.PAGE_END);

        panelContent.setLayout(new java.awt.BorderLayout());
        panelContent.add(bathroomPanel1, java.awt.BorderLayout.CENTER);

        tabPanel.setPreferredSize(new java.awt.Dimension(350, 200));

        logTabContent.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Application Log");
        logTabContent.add(jLabel1, java.awt.BorderLayout.NORTH);

        textAreaLog.setColumns(20);
        textAreaLog.setRows(5);
        textAreaLog.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(textAreaLog);

        logTabContent.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        tabPanel.addTab("Log", logTabContent);

        toiletHoursTabContent.setLayout(new java.awt.BorderLayout());

        jTableStudentBathroomHours.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Department", "School year", "Bathroom Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableStudentBathroomHours.setName(""); // NOI18N
        jTableStudentBathroomHours.setPreferredSize(new java.awt.Dimension(300, 0));
        jTableStudentBathroomHours.setRequestFocusEnabled(false);
        jTableStudentBathroomHours.setRowHeight(25);
        jTableStudentBathroomHours.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableStudentBathroomHours.getTableHeader().setResizingAllowed(false);
        jScrollPane2.setViewportView(jTableStudentBathroomHours);

        toiletHoursTabContent.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        tabPanel.addTab("Toilet Hours", toiletHoursTabContent);

        statusPanel.setLayout(new java.awt.GridLayout(2, 0));

        containersPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Containers"));
        containersPanel.setLayout(new java.awt.GridLayout(2, 2));

        jLabel2.setText("Soap fill status:");
        containersPanel.add(jLabel2);

        labelSoapFill.setText("jLabel4");
        containersPanel.add(labelSoapFill);

        jLabel3.setText("Paper fill status:");
        containersPanel.add(jLabel3);

        labelPaperFill.setText("jLabel5");
        containersPanel.add(labelPaperFill);

        statusPanel.add(containersPanel);

        studentStatsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Students statistics"));
        studentStatsPanel.setLayout(new java.awt.GridLayout(3, 2));

        jLabel6.setText("\"No wash\" times:");
        studentStatsPanel.add(jLabel6);

        labelNoWashTimes.setText("jLabel8");
        studentStatsPanel.add(labelNoWashTimes);

        jLabel7.setText("\"No dry\" times:");
        studentStatsPanel.add(jLabel7);

        labelNoDryTimes.setText("jLabel9");
        studentStatsPanel.add(labelNoDryTimes);

        jLabel4.setText("Times in bathroom:");
        studentStatsPanel.add(jLabel4);

        labelTimesInBathroom.setText("jLabel5");
        studentStatsPanel.add(labelTimesInBathroom);

        statusPanel.add(studentStatsPanel);

        tabPanel.addTab("Status", statusPanel);

        panelContent.add(tabPanel, java.awt.BorderLayout.EAST);

        getContentPane().add(panelContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //Students of the simulation
        Student[] studenti = new Student[]{
            new Student("Luca",SchoolDepartment.Draughtsman, 3, 20),
            new Student("Finke",SchoolDepartment.Visitator, 2, 20),
            new Student("Fadil",SchoolDepartment.Cook, 4, 20),
            new Student("Toscanelli",SchoolDepartment.Chemistry, 1, 20),
            new Student("Lazzarus",SchoolDepartment.ComputerScience, 1, 20)
        };

        //Start the simulation
        new Simulation(studenti,gManager,1000);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    
    public static GuiManager gManager;
    public static boolean bathroomStatus = false;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.BathroomPanel bathroomPanel1;
    private javax.swing.JPanel containersPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTableStudentBathroomHours;
    public javax.swing.JLabel labelDate;
    public javax.swing.JLabel labelNoDryTimes;
    public javax.swing.JLabel labelNoWashTimes;
    public javax.swing.JLabel labelPaperFill;
    public javax.swing.JLabel labelSoapFill;
    public javax.swing.JLabel labelTime;
    public javax.swing.JLabel labelTimesInBathroom;
    private javax.swing.JPanel logTabContent;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelInfos;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JPanel studentStatsPanel;
    private javax.swing.JTabbedPane tabPanel;
    public javax.swing.JTextArea textAreaLog;
    private javax.swing.JPanel toiletHoursTabContent;
    // End of variables declaration//GEN-END:variables
}